apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-solution-deployment
  labels:
    app: random-solution
spec:
  replicas: 3
  selector:
    matchLabels:
      app: random-solution
  template:
    metadata:
      labels:
        app: random-solution
    spec:
      containers:
      - name: random
        image: osmansays/random
        ports:
        - containerPort: 5000
      - name: rproxy
        image: osmansays/rproxy
        ports:
        - containerPort: 80
        - containerPort: 443
