apiVersion: v1
kind: Service
metadata:
  name: random
spec:
  selector:
    app: random-solution
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
    - name: http1
      port: 5000
      targetPort: 5000
